apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbdaas-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mbdaas
  template:
    metadata:
      labels:
        app: mbdaas
    spec:
      containers:
      - name: mbdaas
        image: mbdaas:latest
        ports:
        - containerPort: 8000
